# values-frontend.yaml (프론트엔드 전용)
frontend:
  image:
    repository: byunghyukmin/frontend
    tag: cce30a2dafd04e0281edee924f7600677665da21
    pullPolicy: IfNotPresent

  service:
    name: frontend-service
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30081

  ingress:
    enabled: true
    host: frontend.local
