# values-frontend.yaml (프론트엔드 전용)
frontend:
  image:
    repository: byunghyukmin/frontend
    tag: 647c0e1012850a41cf4582f8faf5295f0e1d86ba
    pullPolicy: IfNotPresent

  service:
    name: frontend-service
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30081

  ingress:
    enabled: true
    host: frontend.local
