# values-frontend.yaml (프론트엔드 전용)
frontend:
  image:
    repository: byunghyukmin/frontend
    tag: d634b1189129232a1ee9460b7d4d5d26e4d78dc0
    pullPolicy: IfNotPresent

  service:
    name: frontend-service
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30081

  ingress:
    enabled: true
    host: frontend.local
