# values-frontend.yaml (프론트엔드 전용)
frontend:
  image:
    repository: byunghyukmin/frontend
    tag: 3e583dd6334539403aabebbf2e1aaffcb2242ba6
    pullPolicy: IfNotPresent

  service:
    name: frontend-service
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30081

  ingress:
    enabled: true
    host: frontend.local
