# values-frontend.yaml (프론트엔드 전용)
frontend:
  image:
    repository: byunghyukmin/frontend
    tag: 685b210d4d37858b2e03ae925d67413e907b2df1
    pullPolicy: IfNotPresent

  service:
    name: frontend-service
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30081

  ingress:
    enabled: true
    host: frontend.local
