replicaCount: 1

image:
  repository: kubeops-backend
  tag: dev
  pullPolicy: Never

backendEnv:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:mariadb://host.minikube.internal:3306/k8s_dashboard
  - name: SPRING_DATASOURCE_USERNAME
    value: root
  - name: SPRING_DATASOURCE_PASSWORD
    value: 1234
  - name: APP_SECURITY_FRONTEND_BASE_URL
    value: http://dashboard.kubeops.local
  - name: APP_KUBERNETES_COMMANDS_ENABLED
    value: "false"
  - name: APP_CORS_ALLOWED_ORIGINS
    value: http://dashboard.kubeops.local
  - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
    value: http://host.minikube.internal:8090/realms/kubeops-local
  - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID
    value: kubeops-web
  - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET
    value: kubeops-local-secret
  - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE
    value: openid,profile,email

service:
  name: springboot-app-service
  type: ClusterIP
  port: 80
  targetPort: 8081

ingress:
  enabled: true
  host: api.kubeops.local
  ingressClassName: nginx

frontend:
  image:
    repository: kubeops-frontend
    tag: dev
    pullPolicy: Never

  service:
    name: frontend-service
    type: ClusterIP
    port: 80
    targetPort: 80

  ingress:
    enabled: true
    host: dashboard.kubeops.local
    ingressClassName: nginx
