replicaCount: 1            # 배포 수
image:                     # 도커 이미지 정보
  repository: byunghyukmin/springboot-app
  tag: dfb6da4249ba8e5e62c8f44a0ae8648ff5a064e6
  pullPolicy: IfNotPresent

service:
  name: springboot-app-service
  type: NodePort
  port: 80
  targetPort: 8081
  nodePort: 30080  # 외부 노출 포트

readinessProbe:
  enabled: true
  path: /
  port: 8081
  initialDelaySeconds: 2
  periodSeconds: 3
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

resources: {}

ingress:
  enabled: true
  host: springboot.local
  port: 8081
  ingressClassName: nginx   

frontend:
  image:
    repository: byunghyukmin/frontend
    tag: b2adc6c589b996201ea7b0c57c13f8091d3f1b39
    pullPolicy: IfNotPresent

  service:
    name: frontend-service
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30081

  ingress:
    enabled: true
    host: frontend.local
