# ----------------------------------------
# 공통 설정
# ----------------------------------------
replicaCount: 1

resources: {}

# ----------------------------------------
# SpringBoot 앱 설정
# ----------------------------------------
image:
  repository: byunghyukmin/springboot-app
<<<<<<< Updated upstream
  tag: a897aada639607ecc4c33d5589a7494d0443f031
=======
  tag: 2a52acfa1b0a366d4e90bb2094eb2e873a049e36
>>>>>>> Stashed changes
  pullPolicy: IfNotPresent

service:
  name: springboot-app-service
  type: NodePort
  port: 80
  targetPort: 8081

readinessProbe:
  enabled: true
  path: /api/health/healthcheck
  port: 8081
  initialDelaySeconds: 5
  periodSeconds: 3
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

ingress:
  enabled: true
  host: springboot.local
  ingressClassName: nginx

# ----------------------------------------
# Frontend 앱 설정
# ----------------------------------------
frontend:
  image:
    repository: byunghyukmin/frontend
    tag: b2adc6c589b996201ea7b0c57c13f8091d3f1b39
    pullPolicy: IfNotPresent

  service:
    name: frontend-service
    type: NodePort
    port: 80
    targetPort: 80

  ingress:
    enabled: true
    host: frontend.local
    ingressClassName: nginx
