replicaCount: 1            # 배포 수
image:                     # 도커 이미지 정보
  repository: byunghyukmin/springboot-app
  tag: fa584b7be0d60065ae8bf6fc3423a484ebfba995
  pullPolicy: IfNotPresent

service:                   # 서비스 설정
  name: springboot-app-service
  type: LoadBalancer
  port: 80
  targetPort: 8081

readinessProbe:            # 헬스 체크 설정
  enabled: true
  path: /
  port: 8081
  initialDelaySeconds: 2
  periodSeconds: 3
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

resources: {}              # 리소스 제한 설정 가능

ingress:
  enabled: true
  host: springboot.local
