replicaCount: 1            # 배포 수
image:                     # 도커 이미지 정보
  repository: byunghyukmin/springboot-app
  tag: 34ca159dd3fa6645e3b7941dd109f6ee5c2170b8
  pullPolicy: IfNotPresent

service:
  name: springboot-app-service
  type: NodePort
  port: 80
  targetPort: 8081
  nodePort: 30080  # 외부 노출 포트

readinessProbe:
  enabled: true
  path: /
  port: 8081
  initialDelaySeconds: 2
  periodSeconds: 3
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

resources: {}

ingress:
  enabled: true
  host: springboot.local

