server:
  port: 8081
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mariadb://mariadb.default.svc.cluster.local:3306/k8s_dashboard
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none                # DB 자동 생성/변경 안함
    show-sql: true                 # SQL 콘솔에 출력
    properties:
      hibernate:
        physical_naming_strategy: com.example.demo.config.jpa.UpperSnakeCaseNamingStrategy
        format_sql: true           # SQL 예쁘게 출력
