apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontend.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.service.name }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80

