apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.service.name }}
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "springboot-app.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "springboot-app.labels" . | nindent 8 }}
        {{- include "springboot-app.frontendSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
