apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    {{- include "springboot-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    {{- include "springboot-app.backendSelectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
