name: CI - Build and Deploy Docker Image with Helm SHA Update

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # GitHub 인증 토큰 사용

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (multi-platform)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./springboot-app/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            byunghyukmin/springboot-app:latest
            byunghyukmin/springboot-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Helm values.yaml with new SHA tag
        run: |
          # Update the tag in values.yaml with the new GitHub SHA
          sed -i "s/^  tag: .*/  tag: ${{ github.sha }}/" ./springboot-helm-chart/values.yaml

          # Configure Git user for GitHub Actions
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Commit and push the updated values.yaml to the repository
          git add ./springboot-helm-chart/values.yaml
          git commit -m "ci: update image tag to ${{ github.sha }}"

          # Push the changes to GitHub using GitHub token
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the GitHub token for authentication

